version: "3"

services:

  #postgres:
  #  container_name: postgres-bot
   # image: postgres:12-alpine
  #  restart: always
  #  env_file:
  #    - .env
  #  environment:
  #    - POSTGRES_PASSWORD=${PG_PASSWORD}
  #    - POSTGRES_USER=${PG_USER}
  #    - POSTGRES_DB=${PG_NAME}
   #   - PGDATA=${PG_DATA}
   # ports:
   #   - ${PG_PORT}:${PG_PORT}
   # expose:
   #   - ${PG_PORT}
   # volumes:
   #   - /usr/src/app/data:/var/lib/postgresql/data/pgdata
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env  
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=5 

    bot:
    container_name: telegram-bot
    image: yanastasya/bot:latest
    restart: always
    env_file:
      - .env
    links:
      #- postgres
      - redis
    depends_on:
    #  - postgres
      - redis

volumes:
  #postgres-data:
  redis:
